var menu_div_dataset=
[
    {
        title1:"前沿技术",
        link1:["微服务","区块链","以太坊","人工智能","机器学习","深度学习","计算机视觉","数据分析&挖掘"],
        title2:"",
        link2:[""],
        recommend:
        [
            {
                src:"./image/menu_div_101.jpg",
                h3:"区块链入门与去中心化应用实战",
                price:"¥199.00",
                level:"初级",
                people:"570"
            },
            {
                src:"./image/menu_div_102.jpg",
                h3:"区块链技术核心概念与原理讲解",
                price:"",
                level:"入门",
                people:"25082"
            },
            {
                src:"./image/menu_div_103.jpg",
                h3:"基于Python玩转人工智能最火框架 TensorFlow应用实践",
                price:"¥299.00",
                level:"中级",
                people:"1279"
            },
            {
                src:"./image/menu_div_104.jpg",
                h3:"Python人工智能常用库Numpy使用入门",
                price:"",
                level:"初级",
                people:"21381"
            },
        ]
    },
    {
        title1:"前端开发",
        link1:["HTML/CSS","JavaScript","Vue.js","React.JS","Angular","Node.js","jQuery","Bootstrap","Sass/Less","WebApp","前端工具"],
        title2:"",
        link2:[""],
        recommend:
        [
            {
                src:"./image/menu_div_201.jpg",
                h3:"HTML5与CSS3实现动态网页",
                price:"¥628.00",
                level:"5步/29课",
                people:"1839"
            },
            {
                src:"./image/menu_div_202.jpg",
                h3:"微信小程序入门与实战 常用组件API开发技巧项目实战",
                price:"¥149.00",
                level:"初级",
                people:"14140"
            },
            {
                src:"./image/menu_div_203.jpg",
                h3:"前端跳槽必备 揭秘一线互联网公司高级前端JavaScript面试",
                price:"¥366.00",
                level:"高级",
                people:"605"
            },
            {
                src:"./image/menu_div_204.jpg",
                h3:"前端JavaScript面试技巧",
                price:"¥149.00",
                level:"初级",
                people:"2819"
            },
        ]
    },
    {
        title1:"后端开发",
        link1:["Java","SpringBoot","Python","爬虫","Django","Go","PHP","C","C++","C#","Ruby"],
        title2:"",
        link2:[""],
        recommend:
        [
            {
                src:"./image/menu_div_301.jpg",
                h3:"C++零基础入门  热门编程语言  二级考试必备",
                price:"¥428.00",
                level:"3步/34课",
                people:"423"
            },
            {
                src:"./image/menu_div_302.jpg",
                h3:"Java并发编程入门与高并发面试",
                price:"¥299.00",
                level:"初级",
                people:"2129"
            },
            {
                src:"./image/menu_div_303.jpg",
                h3:"全网最热Python3入门+进阶 更快上手实际开发",
                price:"¥366.00",
                level:"初级",
                people:"5484"
            },
            {
                src:"./image/menu_div_304.jpg",
                h3:"最火Python3 玩转实用小工具",
                price:"¥166.00",
                level:"初级",
                people:"138"
            },
        ]
    },
    {
        title1:"移动开发",
        link1:["Android","iOS","React","native","WEEX"],
        title2:"",
        link2:[""],
        recommend:
        [
            {
                src:"./image/menu_div_401.jpg",
                h3:"零基础入门Android语法与界面",
                price:"¥499.00",
                level:"5步/43课",
                people:"2058"
            },
            {
                src:"./image/menu_div_402.jpg",
                h3:"新浪微博资深大牛全方位剖析 iOS 高级面试",
                price:"¥366.00",
                level:"高级",
                people:"442"
            },
            {
                src:"./image/menu_div_403.jpg",
                h3:"BAT大牛亲授技能+技巧  Android面试快速充电升级",
                price:"¥288.00",
                level:"中级",
                people:"3103"
            },
            {
                src:"./image/menu_div_404.jpg",
                h3:"Android通用框架设计与完整电商APP开发",
                price:"¥348.00",
                level:"高级",
                people:"1407"
            },
        ]
    },
    {
        title1:"算法&数学",
        link1:["算法与数据结构","数学"],
        title2:"云计算&大数据",
        link2:["大数据","Hadoop","Spark","Hbase","Storm","云计算","AWS","Docker","Kubernetes"],
        recommend:
        [
            {
                src:"./image/menu_div_501.jpg",
                h3:"以慕课网日志分析为例  进入大数据 Spark SQL 的世界",
                price:"¥366.00",
                level:"中级",
                people:"1003"
            },
            {
                src:"./image/menu_div_502.jpg",
                h3:"轻松愉快之玩转SpringData",
                price:"",
                level:"中级",
                people:"23623"
            },
            {
                src:"./image/menu_div_503.jpg",
                h3:"系统学习Docker 践行DevOps理念",
                price:"¥299.00",
                level:"中级",
                people:"763"
            },
            {
                src:"./image/menu_div_504.jpg",
                h3:"HBase入门",
                price:"",
                level:"初级",
                people:"17360"
            },
        ]
    },
    {
        title1:"运维&测试",
        link1:["运维","自动化运维","Linux","测试","功能测试","性能测试","自动化测试","接口测试","安全测试"],
        title2:"数据库",
        link2:["MySQL","Redis","MongoDB","Oracle","SQL","Server","NoSql"],
        recommend:
        [
            {
                src:"./image/menu_div_601.jpg",
                h3:"阿里大牛亲授  阿里云主机(ECS)与CentOS7实战",
                price:"¥288.00",
                level:"中级",
                people:"103"
            },
            {
                src:"./image/menu_div_602.jpg",
                h3:"使用java构建和维护接口自动化测试框架",
                price:"",
                level:"中级",
                people:"18927"
            },
            {
                src:"./image/menu_div_603.jpg",
                h3:"Web自动化测试  Selenium基础到企业应用",
                price:"¥266.00",
                level:"中级",
                people:"905"
            },
            {
                src:"./image/menu_div_604.jpg",
                h3:"Linux系统管理",
                price:"",
                level:"初级",
                people:"61106"
            },
        ]
    },
    {
        title1:"UI设计",
        link1:["模型制作","动效动画","设计基础","设计工具","APPUI设计","产品交互"],
        title2:"游戏",
        link2:["Unity","3D Cocos2d-x"],
        recommend:
        [
            {
                src:"./image/menu_div_701.jpg",
                h3:"移动端App UI 设计入门与实战",
                price:"¥199.00",
                level:"中级",
                people:"359"
            },
            {
                src:"./image/menu_div_702.jpg",
                h3:"高薪设计师必修课 AE移动UI动效设计从入门到实战",
                price:"¥199.00",
                level:"中级",
                people:"100"
            },
            {
                src:"./image/menu_div_703.jpg",
                h3:"Axure入门初体验",
                price:"",
                level:"入门",
                people:"46099"
            },
            {
                src:"./image/menu_div_704.jpg",
                h3:"前端工程师必备的PS技能——切图篇",
                price:"",
                level:"初级",
                people:"230311"
            },
        ]
    }
];